export const HabenQuestions = [
  {
    question: "Ich ___ ein Buch. (Saya ___ sebuah buku.)",
    choices: ["habe", "hast", "hat", "haben"],
    answer: "habe",
    kategori: "haben",
  },
  {
    question: "Du ___ einen Hund. (Kamu ___ seekor anjing.)",
    choices: ["habe", "hast", "hat", "habt"],
    answer: "hast",
    kategori: "haben",
  },
  {
    question: "Er ___ eine Schwester. (Dia ___ seorang saudara perempuan.)",
    choices: ["hat", "habe", "hast", "haben"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Sie ___ eine Katze. (Dia ___ seekor kucing.)",
    choices: ["hast", "hat", "habt", "habe"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Es ___ vier Beine. (Itu ___ empat kaki.)",
    choices: ["hat", "haben", "hast", "habe"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Wir ___ viele Freunde. (Kami ___ banyak teman.)",
    choices: ["haben", "habt", "hat", "hast"],
    answer: "haben",
    kategori: "haben",
  },
  {
    question: "Ihr ___ heute viel Zeit. (Kalian ___ banyak waktu hari ini.)",
    choices: ["habt", "haben", "hat", "hast"],
    answer: "habt",
    kategori: "haben",
  },
  {
    question: "Sie ___ ein Auto. (Mereka ___ sebuah mobil.)",
    choices: ["habe", "hat", "haben", "habt"],
    answer: "haben",
    kategori: "haben",
  },
  {
    question: "Ich ___ Hunger. (Saya ___ lapar.)",
    choices: ["habe", "hast", "hat", "habt"],
    answer: "habe",
    kategori: "haben",
  },
  {
    question: "Du ___ Durst. (Kamu ___ haus.)",
    choices: ["hast", "habe", "haben", "hat"],
    answer: "hast",
    kategori: "haben",
  },
  {
    question: "Er ___ einen Bruder. (Dia ___ seorang saudara laki-laki.)",
    choices: ["hat", "habt", "habe", "hast"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Sie ___ einen Kugelschreiber. (Dia ___ sebuah pena.)",
    choices: ["hat", "habe", "haben", "habt"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Es ___ einen Namen. (Itu ___ sebuah nama.)",
    choices: ["hat", "hast", "habt", "habe"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Wir ___ Unterricht. (Kami ___ pelajaran.)",
    choices: ["haben", "habt", "hat", "hast"],
    answer: "haben",
    kategori: "haben",
  },
  {
    question: "Ihr ___ zwei Lehrer. (Kalian ___ dua guru.)",
    choices: ["habt", "haben", "hat", "habe"],
    answer: "habt",
    kategori: "haben",
  },
  {
    question: "Sie ___ keine Zeit. (Mereka ___ tidak punya waktu.)",
    choices: ["haben", "hat", "hast", "habt"],
    answer: "haben",
    kategori: "haben",
  },
  {
    question: "Ich ___ eine Tasche. (Saya ___ sebuah tas.)",
    choices: ["habe", "hast", "habt", "hat"],
    answer: "habe",
    kategori: "haben",
  },
  {
    question: "Du ___ ein Fahrrad. (Kamu ___ sebuah sepeda.)",
    choices: ["hast", "habe", "haben", "hat"],
    answer: "hast",
    kategori: "haben",
  },
  {
    question:
      "Er ___ heute Deutsch. (Dia ___ pelajaran bahasa Jerman hari ini.)",
    choices: ["hat", "habt", "habe", "hast"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Sie ___ ein Problem. (Dia ___ sebuah masalah.)",
    choices: ["hat", "haben", "habt", "habe"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Es ___ eine rote Farbe. (Itu ___ warna merah.)",
    choices: ["hat", "hast", "haben", "habt"],
    answer: "hat",
    kategori: "haben",
  },
  {
    question: "Wir ___ eine Prüfung. (Kami ___ sebuah ujian.)",
    choices: ["haben", "habt", "hat", "hast"],
    answer: "haben",
    kategori: "haben",
  },
  {
    question: "Ihr ___ ein Haus. (Kalian ___ sebuah rumah.)",
    choices: ["habt", "haben", "hast", "hat"],
    answer: "habt",
    kategori: "haben",
  },
  {
    question:
      "Sie ___ einen Hund und eine Katze. (Mereka ___ seekor anjing dan seekor kucing.)",
    choices: ["haben", "hat", "habt", "habe"],
    answer: "haben",
    kategori: "haben",
  },
  {
    question:
      "Ich ___ heute keine Hausaufgaben. (Saya ___ tidak punya pekerjaan rumah hari ini.)",
    choices: ["habe", "hast", "hat", "haben"],
    answer: "habe",
    kategori: "haben",
  },
];
