export const SeinQuestions = [
  {
    question: "Ich ____ ein Schüler. (Saya ____ seorang murid laki-laki.)",
    choices: ["bin", "bist", "ist", "sind"],
    answer: "bin",
    kategori: "sein",
  },
  {
    question: "Du ____ müde. (Kamu ____ lelah.)",
    choices: ["bin", "bist", "ist", "seid"],
    answer: "bist",
    kategori: "sein",
  },
  {
    question: "Er ____ mein Bruder. (Dia ____ saudara laki-laki saya.)",
    choices: ["ist", "bin", "seid", "sind"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Sie ____ meine Freundin. (Dia ____ teman perempuan saya.)",
    choices: ["bist", "ist", "seid", "bin"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Es ____ kalt. (Itu / cuacanya ____ dingin.)",
    choices: ["ist", "sind", "bist", "seid"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Wir ____ in der Schule. (Kami ____ di sekolah.)",
    choices: ["bin", "bist", "sind", "ist"],
    answer: "sind",
    kategori: "sein",
  },
  {
    question: "Ihr ____ sehr nett. (Kalian ____ sangat baik.)",
    choices: ["seid", "sind", "ist", "bin"],
    answer: "seid",
    kategori: "sein",
  },
  {
    question: "Sie ____ aus Deutschland. (Mereka ____ dari Jerman.)",
    choices: ["ist", "bist", "sind", "bin"],
    answer: "sind",
    kategori: "sein",
  },
  {
    question: "Ich ____ heute glücklich. (Saya ____ bahagia hari ini.)",
    choices: ["bin", "bist", "seid", "ist"],
    answer: "bin",
    kategori: "sein",
  },
  {
    question: "Du ____ mein Freund. (Kamu ____ teman laki-laki saya.)",
    choices: ["bist", "bin", "ist", "sind"],
    answer: "bist",
    kategori: "sein",
  },
  {
    question: "Er ____ Lehrer. (Dia ____ seorang guru laki-laki.)",
    choices: ["ist", "seid", "bin", "bist"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Sie ____ zu Hause. (Dia ____ di rumah.)",
    choices: ["bin", "ist", "seid", "sind"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Es ____ ein Hund. (Itu ____ seekor anjing.)",
    choices: ["ist", "bist", "sind", "seid"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Wir ____ zusammen im Park. (Kami ____ bersama di taman.)",
    choices: ["sind", "seid", "ist", "bin"],
    answer: "sind",
    kategori: "sein",
  },
  {
    question: "Ihr ____ pünktlich. (Kalian ____ tepat waktu.)",
    choices: ["seid", "sind", "bist", "ist"],
    answer: "seid",
    kategori: "sein",
  },
  {
    question: "Sie ____ meine Eltern. (Mereka ____ orang tua saya.)",
    choices: ["bin", "sind", "ist", "bist"],
    answer: "sind",
    kategori: "sein",
  },
  {
    question: "Ich ____ im Klassenzimmer. (Saya ____ di ruang kelas.)",
    choices: ["bin", "bist", "seid", "ist"],
    answer: "bin",
    kategori: "sein",
  },
  {
    question: "Du ____ sehr freundlich. (Kamu ____ sangat ramah.)",
    choices: ["bist", "bin", "sind", "ist"],
    answer: "bist",
    kategori: "sein",
  },
  {
    question: "Er ____ krank. (Dia ____ sakit.)",
    choices: ["ist", "seid", "bin", "bist"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Sie ____ meine Schwester. (Dia ____ saudara perempuan saya.)",
    choices: ["ist", "sind", "bist", "bin"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Es ____ nicht schwer. (Itu ____ tidak sulit.)",
    choices: ["ist", "seid", "sind", "bin"],
    answer: "ist",
    kategori: "sein",
  },
  {
    question: "Wir ____ fertig. (Kami ____ selesai.)",
    choices: ["sind", "ist", "bist", "seid"],
    answer: "sind",
    kategori: "sein",
  },
  {
    question: "Ihr ____ im Bus. (Kalian ____ di bus.)",
    choices: ["seid", "sind", "bin", "ist"],
    answer: "seid",
    kategori: "sein",
  },
  {
    question: "Sie ____ sehr leise. (Mereka ____ sangat pelan.)",
    choices: ["sind", "bist", "ist", "bin"],
    answer: "sind",
    kategori: "sein",
  },
  {
    question: "Ich ____ aus Indonesien. (Saya ____ dari Indonesia.)",
    choices: ["bin", "bist", "ist", "seid"],
    answer: "bin",
    kategori: "sein",
  },
];
