export const VocabQuestions = [
  {
    question: "Guten Morgen.",
    choices: ["selamat pagi", "selamat siang", "selamat malam", "selamat sore"],
    answer: "selamat pagi",
    kategori: "sapaan",
  },
  {
    question: "Guten Tag.",
    choices: ["selamat malam", "selamat siang", "selamat pagi", "sampai jumpa"],
    answer: "selamat siang",
    kategori: "sapaan",
  },
  {
    question: "Guten Abend.",
    choices: ["selamat sore", "selamat malam", "selamat pagi", "terima kasih"],
    answer: "selamat malam",
    kategori: "sapaan",
  },
  {
    question: "Tschüss.",
    choices: ["halo", "tolong", "sampai jumpa", "permisi"],
    answer: "sampai jumpa",
    kategori: "sapaan",
  },
  {
    question: "Hallo.",
    choices: ["halo", "selamat tinggal", "maaf", "ya"],
    answer: "halo",
    kategori: "sapaan",
  },
  {
    question: "Danke.",
    choices: ["tolong", "terima kasih", "maaf", "sama-sama"],
    answer: "terima kasih",
    kategori: "ungkapan",
  },
  {
    question: "Bitte.",
    choices: ["sama-sama / tolong", "maaf", "terima kasih", "permisi"],
    answer: "sama-sama / tolong",
    kategori: "ungkapan",
  },
  {
    question: "Entschuldigung.",
    choices: ["maaf / permisi", "selamat pagi", "terima kasih", "tolong"],
    answer: "maaf / permisi",
    kategori: "ungkapan",
  },
  {
    question: "Ja.",
    choices: ["tidak", "ya", "mungkin", "baik"],
    answer: "ya",
    kategori: "dasar",
  },
  {
    question: "Nein.",
    choices: ["ya", "baik", "tidak", "tolong"],
    answer: "tidak",
    kategori: "dasar",
  },
  {
    question: "Mann.",
    choices: ["wanita", "anak", "pria", "teman"],
    answer: "pria",
    kategori: "orang",
  },
  {
    question: "Frau.",
    choices: ["wanita", "ibu kota", "adik", "nenek"],
    answer: "wanita",
    kategori: "orang",
  },
  {
    question: "Kind.",
    choices: ["anak", "ayah", "ibu", "guru"],
    answer: "anak",
    kategori: "orang",
  },
  {
    question: "Freund.",
    choices: ["tetangga", "teman laki-laki", "ayah", "saudara"],
    answer: "teman laki-laki",
    kategori: "orang",
  },
  {
    question: "Freundin.",
    choices: ["teman perempuan", "ibu", "bibi", "guru"],
    answer: "teman perempuan",
    kategori: "orang",
  },
  {
    question: "Haus.",
    choices: ["sekolah", "rumah", "kamar", "jalan"],
    answer: "rumah",
    kategori: "benda",
  },
  {
    question: "Tür.",
    choices: ["pintu", "jendela", "atap", "lantai"],
    answer: "pintu",
    kategori: "benda",
  },
  {
    question: "Fenster.",
    choices: ["meja", "kursi", "jendela", "dinding"],
    answer: "jendela",
    kategori: "benda",
  },
  {
    question: "Tisch.",
    choices: ["lemari", "pintu", "kursi", "meja"],
    answer: "meja",
    kategori: "benda",
  },
  {
    question: "Stuhl.",
    choices: ["meja", "kursi", "buku", "tas"],
    answer: "kursi",
    kategori: "benda",
  },
  {
    question: "Buch.",
    choices: ["pena", "kertas", "buku", "penghapus"],
    answer: "buku",
    kategori: "benda",
  },
  {
    question: "Auto.",
    choices: ["sepeda", "mobil", "bus", "kereta"],
    answer: "mobil",
    kategori: "transportasi",
  },
  {
    question: "Fahrrad.",
    choices: ["motor", "mobil", "sepeda", "jalan kaki"],
    answer: "sepeda",
    kategori: "transportasi",
  },
  {
    question: "Straße.",
    choices: ["rumah", "jalan", "jembatan", "pasar"],
    answer: "jalan",
    kategori: "tempat",
  },
  {
    question: "Schule.",
    choices: ["kantor", "sekolah", "rumah sakit", "toko"],
    answer: "sekolah",
    kategori: "tempat",
  },
  {
    question: "Wasser.",
    choices: ["kopi", "teh", "air", "susu"],
    answer: "air",
    kategori: "makanan dan minuman",
  },
  {
    question: "Brot.",
    choices: ["nasi", "roti", "buah", "sup"],
    answer: "roti",
    kategori: "makanan dan minuman",
  },
  {
    question: "Milch.",
    choices: ["air", "jus", "susu", "kopi"],
    answer: "susu",
    kategori: "makanan dan minuman",
  },
  {
    question: "Apfel.",
    choices: ["jeruk", "apel", "anggur", "pisang"],
    answer: "apel",
    kategori: "makanan dan minuman",
  },
  {
    question: "Kaffee.",
    choices: ["teh", "kopi", "susu", "air"],
    answer: "kopi",
    kategori: "makanan dan minuman",
  },
  {
    question: "Tee.",
    choices: ["kopi", "air", "teh", "jus"],
    answer: "teh",
    kategori: "makanan dan minuman",
  },
  {
    question: "Hund.",
    choices: ["kucing", "anjing", "burung", "ikan"],
    answer: "anjing",
    kategori: "hewan",
  },
  {
    question: "Katze.",
    choices: ["anjing", "ikan", "kucing", "kelinci"],
    answer: "kucing",
    kategori: "hewan",
  },
  {
    question: "Vogel.",
    choices: ["burung", "ular", "sapi", "ayam"],
    answer: "burung",
    kategori: "hewan",
  },
  {
    question: "Fisch.",
    choices: ["ikan", "burung", "kucing", "kuda"],
    answer: "ikan",
    kategori: "hewan",
  },
  {
    question: "Rot.",
    choices: ["biru", "merah", "kuning", "hijau"],
    answer: "merah",
    kategori: "warna",
  },
  {
    question: "Blau.",
    choices: ["biru", "merah", "hitam", "putih"],
    answer: "biru",
    kategori: "warna",
  },
  {
    question: "Grün.",
    choices: ["kuning", "merah", "hijau", "biru"],
    answer: "hijau",
    kategori: "warna",
  },
  {
    question: "Gelb.",
    choices: ["ungu", "kuning", "oranye", "cokelat"],
    answer: "kuning",
    kategori: "warna",
  },
  {
    question: "Schwarz.",
    choices: ["putih", "abu-abu", "hitam", "biru"],
    answer: "hitam",
    kategori: "warna",
  },
  {
    question: "Weiß.",
    choices: ["putih", "hitam", "kuning", "merah"],
    answer: "putih",
    kategori: "warna",
  },
  {
    question: "Eins.",
    choices: ["satu", "dua", "tiga", "empat"],
    answer: "satu",
    kategori: "angka",
  },
  {
    question: "Zwei.",
    choices: ["satu", "dua", "lima", "enam"],
    answer: "dua",
    kategori: "angka",
  },
  {
    question: "Drei.",
    choices: ["dua", "empat", "tiga", "lima"],
    answer: "tiga",
    kategori: "angka",
  },
  {
    question: "Vier.",
    choices: ["empat", "tiga", "dua", "satu"],
    answer: "empat",
    kategori: "angka",
  },
  {
    question: "Fünf.",
    choices: ["empat", "lima", "enam", "tujuh"],
    answer: "lima",
    kategori: "angka",
  },
  {
    question: "Groß.",
    choices: ["kecil", "besar", "panjang", "pendek"],
    answer: "besar",
    kategori: "sifat",
  },
  {
    question: "Klein.",
    choices: ["besar", "tinggi", "kecil", "cepat"],
    answer: "kecil",
    kategori: "sifat",
  },
  {
    question: "Gut.",
    choices: ["buruk", "baik", "sulit", "mudah"],
    answer: "baik",
    kategori: "sifat",
  },
  {
    question: "Schlecht.",
    choices: ["mudah", "baik", "buruk", "cepat"],
    answer: "buruk",
    kategori: "sifat",
  },
  {
    question: "Auf Wiedersehen.",
    choices: ["selamat tinggal", "selamat pagi", "permisi", "terima kasih"],
    answer: "selamat tinggal",
    kategori: "sapaan",
  },
  {
    question: "Bis morgen.",
    choices: ["sampai besok", "sampai nanti", "selamat malam", "hati-hati"],
    answer: "sampai besok",
    kategori: "sapaan",
  },
  {
    question: "Wie geht's?",
    choices: [
      "siapa namamu?",
      "apa kabar?",
      "dari mana kamu?",
      "berapa umurmu?",
    ],
    answer: "apa kabar?",
    kategori: "sapaan",
  },
  {
    question: "Willkommen.",
    choices: [
      "selamat jalan",
      "silakan duduk",
      "selamat datang",
      "terima kasih",
    ],
    answer: "selamat datang",
    kategori: "sapaan",
  },
  {
    question: "Bis später.",
    choices: ["sampai nanti", "selamat pagi", "cepatlah", "permisi"],
    answer: "sampai nanti",
    kategori: "sapaan",
  },
  {
    question: "Gern geschehen.",
    choices: ["sama-sama", "tolong saya", "permisi", "maaf"],
    answer: "sama-sama",
    kategori: "ungkapan",
  },
  {
    question: "Kein Problem.",
    choices: ["tidak tahu", "tidak masalah", "jangan begitu", "sangat sulit"],
    answer: "tidak masalah",
    kategori: "ungkapan",
  },
  {
    question: "Viel Glück.",
    choices: [
      "semoga cepat sembuh",
      "selamat makan",
      "semoga beruntung",
      "hati-hati",
    ],
    answer: "semoga beruntung",
    kategori: "ungkapan",
  },
  {
    question: "Gute Reise.",
    choices: [
      "perjalanan yang baik",
      "istirahat yang cukup",
      "cepat sembuh",
      "selamat belajar",
    ],
    answer: "perjalanan yang baik",
    kategori: "ungkapan",
  },
  {
    question: "Alles klar.",
    choices: [
      "semua jelas / oke",
      "semua salah",
      "tidak bisa",
      "sudah selesai",
    ],
    answer: "semua jelas / oke",
    kategori: "ungkapan",
  },
  {
    question: "Vielleicht.",
    choices: ["tentu", "mungkin", "tidak pernah", "selalu"],
    answer: "mungkin",
    kategori: "dasar",
  },
  {
    question: "Immer.",
    choices: ["sering", "kadang-kadang", "selalu", "jarang"],
    answer: "selalu",
    kategori: "dasar",
  },
  {
    question: "Nie.",
    choices: ["sering", "tidak pernah", "mungkin", "segera"],
    answer: "tidak pernah",
    kategori: "dasar",
  },
  {
    question: "Heute.",
    choices: ["kemarin", "besok", "hari ini", "lusa"],
    answer: "hari ini",
    kategori: "dasar",
  },
  {
    question: "Morgen.",
    choices: ["pagi", "besok", "malam", "siang"],
    answer: "besok",
    kategori: "dasar",
  },
  {
    question: "Mutter.",
    choices: ["ayah", "ibu", "nenek", "adik perempuan"],
    answer: "ibu",
    kategori: "orang",
  },
  {
    question: "Vater.",
    choices: ["paman", "ayah", "kakak laki-laki", "teman"],
    answer: "ayah",
    kategori: "orang",
  },
  {
    question: "Bruder.",
    choices: ["saudara perempuan", "adik", "saudara laki-laki", "paman"],
    answer: "saudara laki-laki",
    kategori: "orang",
  },
  {
    question: "Schwester.",
    choices: ["saudara perempuan", "ibu", "bibi", "nenek"],
    answer: "saudara perempuan",
    kategori: "orang",
  },
  {
    question: "Lehrer.",
    choices: ["murid", "dokter", "guru laki-laki", "tetangga"],
    answer: "guru laki-laki",
    kategori: "orang",
  },
  {
    question: "Lampe.",
    choices: ["lampu", "meja", "tas", "sepatu"],
    answer: "lampu",
    kategori: "benda",
  },
  {
    question: "Tasche.",
    choices: ["buku", "tas", "pena", "pintu"],
    answer: "tas",
    kategori: "benda",
  },
  {
    question: "Uhr.",
    choices: ["jam", "cermin", "gelas", "kunci"],
    answer: "jam",
    kategori: "benda",
  },
  {
    question: "Spiegel.",
    choices: ["jendela", "cermin", "lemari", "lantai"],
    answer: "cermin",
    kategori: "benda",
  },
  {
    question: "Schlüssel.",
    choices: ["kunci", "sendok", "garpu", "sabuk"],
    answer: "kunci",
    kategori: "benda",
  },
  {
    question: "Bus.",
    choices: ["mobil", "bus", "kereta", "sepeda"],
    answer: "bus",
    kategori: "transportasi",
  },
  {
    question: "Zug.",
    choices: ["kapal", "kereta", "pesawat", "motor"],
    answer: "kereta",
    kategori: "transportasi",
  },
  {
    question: "Flugzeug.",
    choices: ["sepeda", "mobil", "pesawat", "bus"],
    answer: "pesawat",
    kategori: "transportasi",
  },
  {
    question: "Schiff.",
    choices: ["kapal", "mobil", "truk", "helikopter"],
    answer: "kapal",
    kategori: "transportasi",
  },
  {
    question: "Motorrad.",
    choices: ["sepeda", "motor", "kereta", "bus"],
    answer: "motor",
    kategori: "transportasi",
  },
  {
    question: "Markt.",
    choices: ["pasar", "rumah", "kelas", "kantor"],
    answer: "pasar",
    kategori: "tempat",
  },
  {
    question: "Krankenhaus.",
    choices: ["apotek", "sekolah", "rumah sakit", "stasiun"],
    answer: "rumah sakit",
    kategori: "tempat",
  },
  {
    question: "Bahnhof.",
    choices: ["bandara", "stasiun", "kantor polisi", "jembatan"],
    answer: "stasiun",
    kategori: "tempat",
  },
  {
    question: "Restaurant.",
    choices: ["restoran", "pasar", "hotel", "sekolah"],
    answer: "restoran",
    kategori: "tempat",
  },
  {
    question: "Park.",
    choices: ["taman", "jalan", "gedung", "kebun"],
    answer: "taman",
    kategori: "tempat",
  },
  {
    question: "Reis.",
    choices: ["mie", "sup", "nasi", "roti"],
    answer: "nasi",
    kategori: "makanan dan minuman",
  },
  {
    question: "Ei.",
    choices: ["daging", "telur", "ikan", "keju"],
    answer: "telur",
    kategori: "makanan dan minuman",
  },
  {
    question: "Saft.",
    choices: ["air", "jus", "teh", "kopi"],
    answer: "jus",
    kategori: "makanan dan minuman",
  },
  {
    question: "Banane.",
    choices: ["apel", "pisang", "anggur", "mangga"],
    answer: "pisang",
    kategori: "makanan dan minuman",
  },
  {
    question: "Suppe.",
    choices: ["sup", "roti", "nasi", "susu"],
    answer: "sup",
    kategori: "makanan dan minuman",
  },
  {
    question: "Pferd.",
    choices: ["sapi", "kuda", "kambing", "ayam"],
    answer: "kuda",
    kategori: "hewan",
  },
  {
    question: "Kuh.",
    choices: ["domba", "sapi", "kucing", "ikan"],
    answer: "sapi",
    kategori: "hewan",
  },
  {
    question: "Maus.",
    choices: ["kelinci", "tikus", "burung", "kambing"],
    answer: "tikus",
    kategori: "hewan",
  },
  {
    question: "Hase.",
    choices: ["kelinci", "kuda", "anjing", "ayam"],
    answer: "kelinci",
    kategori: "hewan",
  },
  {
    question: "Ente.",
    choices: ["bebek", "elang", "ayam", "ikan"],
    answer: "bebek",
    kategori: "hewan",
  },
  {
    question: "Braun.",
    choices: ["merah", "cokelat", "ungu", "putih"],
    answer: "cokelat",
    kategori: "warna",
  },
  {
    question: "Grau.",
    choices: ["abu-abu", "hitam", "biru", "merah"],
    answer: "abu-abu",
    kategori: "warna",
  },
  {
    question: "Sechs.",
    choices: ["lima", "enam", "tujuh", "delapan"],
    answer: "enam",
    kategori: "angka",
  },
  {
    question: "Sieben.",
    choices: ["tujuh", "enam", "delapan", "sembilan"],
    answer: "tujuh",
    kategori: "angka",
  },
  {
    question: "Schnell.",
    choices: ["lambat", "cepat", "besar", "pendek"],
    answer: "cepat",
    kategori: "sifat",
  },
  {
    question: "Bis bald.",
    choices: [
      "sampai nanti",
      "sampai jumpa lagi",
      "selamat malam",
      "hati-hati",
    ],
    answer: "sampai jumpa lagi",
    kategori: "sapaan",
  },
  {
    question: "Gute Nacht.",
    choices: ["selamat malam", "selamat pagi", "selamat siang", "selamat sore"],
    answer: "selamat malam",
    kategori: "sapaan",
  },
  {
    question: "Schönen Tag noch.",
    choices: [
      "semoga harimu menyenangkan",
      "selamat datang",
      "tolong ulangi",
      "apa kabar",
    ],
    answer: "semoga harimu menyenangkan",
    kategori: "sapaan",
  },
  {
    question: "Bis dann.",
    choices: ["sampai nanti", "permisi", "terima kasih", "selamat tidur"],
    answer: "sampai nanti",
    kategori: "sapaan",
  },
  {
    question: "Servus.",
    choices: ["halo / dadah", "maaf", "tolong", "sama-sama"],
    answer: "halo / dadah",
    kategori: "sapaan",
  },
  {
    question: "Keine Ursache.",
    choices: [
      "tidak apa-apa / sama-sama",
      "jangan lupa",
      "saya tidak tahu",
      "sangat bagus",
    ],
    answer: "tidak apa-apa / sama-sama",
    kategori: "ungkapan",
  },
  {
    question: "Gute Besserung.",
    choices: [
      "selamat ulang tahun",
      "semoga cepat sembuh",
      "hati-hati di jalan",
      "selamat datang",
    ],
    answer: "semoga cepat sembuh",
    kategori: "ungkapan",
  },
  {
    question: "Vorsicht.",
    choices: ["cepat", "awas / hati-hati", "diam", "semangat"],
    answer: "awas / hati-hati",
    kategori: "ungkapan",
  },
  {
    question: "Kein Ahnung.",
    choices: ["tidak masalah", "tidak tahu", "tentu saja", "sudah selesai"],
    answer: "tidak tahu",
    kategori: "ungkapan",
  },
  {
    question: "Natürlich.",
    choices: ["tentu saja", "mungkin", "jarang", "tidak pernah"],
    answer: "tentu saja",
    kategori: "ungkapan",
  },
  {
    question: "Gestern.",
    choices: ["hari ini", "besok", "kemarin", "lusa"],
    answer: "kemarin",
    kategori: "dasar",
  },
  {
    question: "Jetzt.",
    choices: ["nanti", "kemarin", "sekarang", "sebentar lagi"],
    answer: "sekarang",
    kategori: "dasar",
  },
  {
    question: "Später.",
    choices: ["lebih awal", "nanti", "sekarang", "kemarin"],
    answer: "nanti",
    kategori: "dasar",
  },
  {
    question: "Früh.",
    choices: ["terlambat", "awal / pagi", "malam", "sore"],
    answer: "awal / pagi",
    kategori: "dasar",
  },
  {
    question: "Zusammen.",
    choices: ["sendiri", "bersama", "cepat", "diam"],
    answer: "bersama",
    kategori: "dasar",
  },
  {
    question: "Lehrerin.",
    choices: ["guru perempuan", "murid perempuan", "ibu", "dokter perempuan"],
    answer: "guru perempuan",
    kategori: "orang",
  },
  {
    question: "Schüler.",
    choices: ["guru laki-laki", "murid laki-laki", "ayah", "teman laki-laki"],
    answer: "murid laki-laki",
    kategori: "orang",
  },
  {
    question: "Schülerin.",
    choices: ["murid perempuan", "guru perempuan", "adik perempuan", "bibi"],
    answer: "murid perempuan",
    kategori: "orang",
  },
  {
    question: "Nachbar.",
    choices: ["saudara", "tetangga laki-laki", "teman", "kakek"],
    answer: "tetangga laki-laki",
    kategori: "orang",
  },
  {
    question: "Nachbarin.",
    choices: [
      "tetangga perempuan",
      "nenek",
      "saudara perempuan",
      "murid perempuan",
    ],
    answer: "tetangga perempuan",
    kategori: "orang",
  },
  {
    question: "Handy.",
    choices: ["telepon genggam", "jam tangan", "tas", "buku"],
    answer: "telepon genggam",
    kategori: "benda",
  },
  {
    question: "Kugelschreiber.",
    choices: ["pensil", "pena", "penghapus", "penggaris"],
    answer: "pena",
    kategori: "benda",
  },
  {
    question: "Bleistift.",
    choices: ["pena", "pensil", "kertas", "tas"],
    answer: "pensil",
    kategori: "benda",
  },
  {
    question: "Papier.",
    choices: ["kertas", "buku", "papan", "pena"],
    answer: "kertas",
    kategori: "benda",
  },
  {
    question: "Brille.",
    choices: ["sepatu", "topi", "kacamata", "jaket"],
    answer: "kacamata",
    kategori: "benda",
  },
  {
    question: "Taxi.",
    choices: ["bus", "taksi", "sepeda", "kereta"],
    answer: "taksi",
    kategori: "transportasi",
  },
  {
    question: "Lastwagen.",
    choices: ["mobil", "truk", "motor", "kapal"],
    answer: "truk",
    kategori: "transportasi",
  },
  {
    question: "Straßenbahn.",
    choices: ["trem", "kereta bawah tanah", "bus", "kapal"],
    answer: "trem",
    kategori: "transportasi",
  },
  {
    question: "U-Bahn.",
    choices: ["kereta bawah tanah", "sepeda", "bus", "pesawat"],
    answer: "kereta bawah tanah",
    kategori: "transportasi",
  },
  {
    question: "Boot.",
    choices: ["kapal kecil / perahu", "kereta", "mobil", "bus"],
    answer: "kapal kecil / perahu",
    kategori: "transportasi",
  },
  {
    question: "Hotel.",
    choices: ["hotel", "restoran", "stasiun", "kantor"],
    answer: "hotel",
    kategori: "tempat",
  },
  {
    question: "Bibliothek.",
    choices: ["toko buku", "perpustakaan", "kelas", "kantor pos"],
    answer: "perpustakaan",
    kategori: "tempat",
  },
  {
    question: "Küche.",
    choices: ["dapur", "kamar tidur", "ruang tamu", "kamar mandi"],
    answer: "dapur",
    kategori: "tempat",
  },
  {
    question: "Zimmer.",
    choices: ["jalan", "kamar", "taman", "jembatan"],
    answer: "kamar",
    kategori: "tempat",
  },
  {
    question: "Büro.",
    choices: ["kantor", "kelas", "pasar", "rumah"],
    answer: "kantor",
    kategori: "tempat",
  },
  {
    question: "Käse.",
    choices: ["keju", "telur", "mentega", "daging"],
    answer: "keju",
    kategori: "makanan dan minuman",
  },
  {
    question: "Fleisch.",
    choices: ["ikan", "daging", "sup", "nasi"],
    answer: "daging",
    kategori: "makanan dan minuman",
  },
  {
    question: "Zucker.",
    choices: ["garam", "gula", "lada", "tepung"],
    answer: "gula",
    kategori: "makanan dan minuman",
  },
  {
    question: "Salz.",
    choices: ["garam", "gula", "teh", "susu"],
    answer: "garam",
    kategori: "makanan dan minuman",
  },
  {
    question: "Orange.",
    choices: ["jeruk", "apel", "pir", "pisang"],
    answer: "jeruk",
    kategori: "makanan dan minuman",
  },
  {
    question: "Schaf.",
    choices: ["domba", "kambing", "sapi", "kelinci"],
    answer: "domba",
    kategori: "hewan",
  },
  {
    question: "Ziege.",
    choices: ["kuda", "kambing", "bebek", "ayam"],
    answer: "kambing",
    kategori: "hewan",
  },
  {
    question: "Huhn.",
    choices: ["ayam", "burung", "bebek", "ikan"],
    answer: "ayam",
    kategori: "hewan",
  },
  {
    question: "Bär.",
    choices: ["harimau", "beruang", "serigala", "rubah"],
    answer: "beruang",
    kategori: "hewan",
  },
  {
    question: "Frosch.",
    choices: ["ular", "katak", "ikan", "burung"],
    answer: "katak",
    kategori: "hewan",
  },
  {
    question: "Orange.",
    choices: ["ungu", "oranye", "merah", "cokelat"],
    answer: "oranye",
    kategori: "warna",
  },
  {
    question: "Rosa.",
    choices: ["merah muda", "ungu", "biru", "kuning"],
    answer: "merah muda",
    kategori: "warna",
  },
  {
    question: "Acht.",
    choices: ["tujuh", "delapan", "sembilan", "sepuluh"],
    answer: "delapan",
    kategori: "angka",
  },
  {
    question: "Neun.",
    choices: ["delapan", "sepuluh", "sembilan", "tujuh"],
    answer: "sembilan",
    kategori: "angka",
  },
  {
    question: "Langsam.",
    choices: ["lambat", "cepat", "besar", "tinggi"],
    answer: "lambat",
    kategori: "sifat",
  },
  {
    question: "Mahlzeit.",
    choices: [
      "selamat makan",
      "selamat pagi",
      "selamat datang",
      "sampai jumpa",
    ],
    answer: "selamat makan",
    kategori: "sapaan",
  },
  {
    question: "Schlaf gut.",
    choices: [
      "tidur yang nyenyak",
      "hati-hati di jalan",
      "sampai nanti",
      "cepat sembuh",
    ],
    answer: "tidur yang nyenyak",
    kategori: "sapaan",
  },
  {
    question: "Bis gleich.",
    choices: [
      "sampai sebentar lagi",
      "sampai besok",
      "sampai minggu depan",
      "selamat malam",
    ],
    answer: "sampai sebentar lagi",
    kategori: "sapaan",
  },
  {
    question: "Grüß dich.",
    choices: ["halo", "permisi", "terima kasih", "maaf"],
    answer: "halo",
    kategori: "sapaan",
  },
  {
    question: "Guten Appetit.",
    choices: [
      "selamat makan",
      "selamat tidur",
      "selamat belajar",
      "selamat jalan",
    ],
    answer: "selamat makan",
    kategori: "sapaan",
  },
  {
    question: "Ich verstehe.",
    choices: ["saya lupa", "saya mengerti", "saya tidak tahu", "saya lapar"],
    answer: "saya mengerti",
    kategori: "ungkapan",
  },
  {
    question: "Ich weiß nicht.",
    choices: [
      "saya sudah tahu",
      "saya tidak tahu",
      "saya senang",
      "saya setuju",
    ],
    answer: "saya tidak tahu",
    kategori: "ungkapan",
  },
  {
    question: "Keine Sorge.",
    choices: [
      "jangan khawatir",
      "jangan berisik",
      "jangan terlambat",
      "jangan lupa",
    ],
    answer: "jangan khawatir",
    kategori: "ungkapan",
  },
  {
    question: "Gerne.",
    choices: [
      "dengan senang hati",
      "sangat sulit",
      "terlalu mahal",
      "sudah selesai",
    ],
    answer: "dengan senang hati",
    kategori: "ungkapan",
  },
  {
    question: "Ein Moment, bitte.",
    choices: [
      "sebentar, tolong",
      "silakan masuk",
      "tolong duduk",
      "saya permisi",
    ],
    answer: "sebentar, tolong",
    kategori: "ungkapan",
  },
  {
    question: "Oft.",
    choices: ["sering", "jarang", "selalu", "kadang-kadang"],
    answer: "sering",
    kategori: "dasar",
  },
  {
    question: "Selten.",
    choices: ["kadang-kadang", "sering", "jarang", "selalu"],
    answer: "jarang",
    kategori: "dasar",
  },
  {
    question: "Bald.",
    choices: ["sebentar lagi", "kemarin", "perlahan", "sendiri"],
    answer: "sebentar lagi",
    kategori: "dasar",
  },
  {
    question: "Links.",
    choices: ["kanan", "kiri", "atas", "bawah"],
    answer: "kiri",
    kategori: "dasar",
  },
  {
    question: "Rechts.",
    choices: ["depan", "belakang", "kanan", "kiri"],
    answer: "kanan",
    kategori: "dasar",
  },
  {
    question: "Familie.",
    choices: ["sekolah", "keluarga", "tetangga", "teman"],
    answer: "keluarga",
    kategori: "orang",
  },
  {
    question: "Eltern.",
    choices: ["orang tua", "anak-anak", "guru-guru", "saudara"],
    answer: "orang tua",
    kategori: "orang",
  },
  {
    question: "Sohn.",
    choices: ["anak perempuan", "saudara laki-laki", "anak laki-laki", "ayah"],
    answer: "anak laki-laki",
    kategori: "orang",
  },
  {
    question: "Tochter.",
    choices: ["ibu", "anak perempuan", "saudara perempuan", "bibi"],
    answer: "anak perempuan",
    kategori: "orang",
  },
  {
    question: "Baby.",
    choices: ["remaja", "bayi", "anak", "nenek"],
    answer: "bayi",
    kategori: "orang",
  },
  {
    question: "Heft.",
    choices: ["buku tulis", "pena", "tas", "meja"],
    answer: "buku tulis",
    kategori: "benda",
  },
  {
    question: "Radiergummi.",
    choices: ["penggaris", "penghapus", "pensil", "spidol"],
    answer: "penghapus",
    kategori: "benda",
  },
  {
    question: "Lineal.",
    choices: ["penggaris", "penghapus", "kertas", "pena"],
    answer: "penggaris",
    kategori: "benda",
  },
  {
    question: "Flasche.",
    choices: ["botol", "gelas", "piring", "sendok"],
    answer: "botol",
    kategori: "benda",
  },
  {
    question: "Glas.",
    choices: ["mangkuk", "gelas", "cangkir", "botol"],
    answer: "gelas",
    kategori: "benda",
  },
  {
    question: "Helikopter.",
    choices: ["helikopter", "pesawat", "kapal", "truk"],
    answer: "helikopter",
    kategori: "transportasi",
  },
  {
    question: "Fähre.",
    choices: ["feri", "bus", "sepeda", "trem"],
    answer: "feri",
    kategori: "transportasi",
  },
  {
    question: "Lieferwagen.",
    choices: [
      "mobil balap",
      "mobil van pengantar",
      "sepeda motor",
      "kereta cepat",
    ],
    answer: "mobil van pengantar",
    kategori: "transportasi",
  },
  {
    question: "Roller.",
    choices: ["skuter", "kapal", "truk", "kereta"],
    answer: "skuter",
    kategori: "transportasi",
  },
  {
    question: "Bahnsteig.",
    choices: ["halte", "peron", "bandara", "pelabuhan"],
    answer: "peron",
    kategori: "transportasi",
  },
  {
    question: "Supermarkt.",
    choices: ["pasar tradisional", "supermarket", "sekolah", "perpustakaan"],
    answer: "supermarket",
    kategori: "tempat",
  },
  {
    question: "Apotheke.",
    choices: ["rumah sakit", "apotek", "kantor polisi", "stasiun"],
    answer: "apotek",
    kategori: "tempat",
  },
  {
    question: "Bäckerei.",
    choices: ["toko roti", "toko buku", "restoran", "kafe"],
    answer: "toko roti",
    kategori: "tempat",
  },
  {
    question: "Toilette.",
    choices: ["dapur", "toilet", "taman", "ruang tamu"],
    answer: "toilet",
    kategori: "tempat",
  },
  {
    question: "Wohnzimmer.",
    choices: ["kamar tidur", "ruang tamu", "teras", "garasi"],
    answer: "ruang tamu",
    kategori: "tempat",
  },
  {
    question: "Butter.",
    choices: ["mentega", "keju", "gula", "garam"],
    answer: "mentega",
    kategori: "makanan dan minuman",
  },
  {
    question: "Kartoffel.",
    choices: ["tomat", "kentang", "wortel", "bawang"],
    answer: "kentang",
    kategori: "makanan dan minuman",
  },
  {
    question: "Tomate.",
    choices: ["cabai", "tomat", "apel", "pir"],
    answer: "tomat",
    kategori: "makanan dan minuman",
  },
  {
    question: "Wurst.",
    choices: ["sosis", "sup", "ikan", "nasi"],
    answer: "sosis",
    kategori: "makanan dan minuman",
  },
  {
    question: "Wassermelonе.",
    choices: ["melon", "semangka", "anggur", "stroberi"],
    answer: "semangka",
    kategori: "makanan dan minuman",
  },
  {
    question: "Schwein.",
    choices: ["babi", "domba", "ayam", "rubah"],
    answer: "babi",
    kategori: "hewan",
  },
  {
    question: "Wolf.",
    choices: ["harimau", "serigala", "beruang", "rubah"],
    answer: "serigala",
    kategori: "hewan",
  },
  {
    question: "Fuchs.",
    choices: ["rubah", "serigala", "beruang", "katak"],
    answer: "rubah",
    kategori: "hewan",
  },
  {
    question: "Schildkröte.",
    choices: ["kura-kura", "ular", "katak", "burung"],
    answer: "kura-kura",
    kategori: "hewan",
  },
  {
    question: "Biene.",
    choices: ["lalat", "lebah", "semut", "kupu-kupu"],
    answer: "lebah",
    kategori: "hewan",
  },
  {
    question: "Lila.",
    choices: ["ungu", "merah muda", "cokelat", "abu-abu"],
    answer: "ungu",
    kategori: "warna",
  },
  {
    question: "Zehn.",
    choices: ["sembilan", "sepuluh", "sebelas", "dua belas"],
    answer: "sepuluh",
    kategori: "angka",
  },
  {
    question: "Elf.",
    choices: ["sepuluh", "dua belas", "sebelas", "tiga belas"],
    answer: "sebelas",
    kategori: "angka",
  },
  {
    question: "Zwölf.",
    choices: ["dua belas", "sebelas", "tiga belas", "empat belas"],
    answer: "dua belas",
    kategori: "angka",
  },
  {
    question: "Hoch.",
    choices: ["pendek", "tinggi", "rendah", "besar"],
    answer: "tinggi",
    kategori: "sifat",
  },
];

export const Allcategories = [
  "sapaan",
  "ungkapan",
  "dasar",
  "orang",
  "benda",
  "transportasi",
  "tempat",
  "makanan dan minuman",
  "hewan",
  "warna",
  "angka",
  "sifat",
];
